### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by saazrai** [laravel-notification-channels/plivo#16]
Does it support Laravel 5.4?

**Comment by cthorne91** [comment]
This package does not currently support Laravel 5.4. Pull request #17 has been submitted to add support.

**Comment by koomai** [comment]
PR Merged

**Comment by saazrai** [comment]
$ composer require laravel-notification-channels/plivo
Using version ^1.0 for laravel-notification-channels/plivo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: don't install laravel-notification-channels/plivo v1.0.2
- Conclusion: don't install laravel-notification-channels/plivo v1.0.1
- Conclusion: remove laravel/framework v5.4.15
- Installation request for laravel-notification-channels/plivo ^1.0 -> satisfiable by laravel-notification-channels/plivo[v1.0.0, v1.0.1, v1.0.2].
- Conclusion: don't install laravel/framework v5.4.15
- laravel-notification-channels/plivo v1.0.0 requires illuminate/events 5.3.* -> satisfiable by illuminate/events[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
- don't install illuminate/events v5.3.0|don't install laravel/framework v5.4.15
- don't install illuminate/events v5.3.16|don't install laravel/framework v5.4.15
- don't install illuminate/events v5.3.23|don't install laravel/framework v5.4.15
- don't install illuminate/events v5.3.4|don't install laravel/framework v5.4.15
- Installation request for laravel/framework == 5.4.15.0 -> satisfiable by laravel/framework[v5.4.15].

Installation failed, reverting ./composer.json to its original content.

**Comment by cthorne91** [comment]
@saazrai, See #20. From what I understand we're just waiting on @themsaid to update packagist.
