### ISSUE TITLE
Update packagist package to support laravel 5.5

### ISSUE THREAD

**Issue by Henokv** [laravel-notification-channels/plivo#22]
Just noticed the repo now supports laravel 5.5 but packagist still only accepts 5.4.
Could you add a new release so the package will be compatible with 5.5? @koomai

**Comment by koomai** [comment]
Unfortunately, I don't have access to packagist for this github repo. It seemed like a good idea first, but I might as well have maintained this under my own account.

**Comment by cayaner** [comment]
Any Update!

**Comment by Henokv** [comment]
Hi,
Normally you should be able to update packagist by adding a release version (semantic version) tag to your repo.
It should update on packagist.

**Comment by koomai** [comment]
Had the same issue before with not auto-updating. Tagging hasn't helped. Need to force an update on Packagist and I don't have access.

**Comment by koomai** [comment]
Duplicate of #20
