### ISSUE TITLE
Erro on Laravel 6.18.3 Unresolvable dependency resolving [Parameter #0 

### ISSUE THREAD

**Issue by achabert** [laravel-notification-channels/plivo#33]
Hi, 
Could you help to solve it?

Illuminate\Contracts\Container\BindingResolutionException
Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class NotificationChannels\Plivo\Plivo

<img width="963" alt="Captura de Tela 2020-04-02 às 21 45 57" src="https://user-images.githubusercontent.com/1642044/78312820-5c409000-752b-11ea-86bc-ac1a48ef8135.png">

**Comment by mikelito859** [comment]
Any suggestion??

**Comment by zayaets** [comment]
Got the same error Laravel 7, 
config/app.php, in 'providers' array add 
\NotificationChannels\Plivo\PlivoServiceProvider::class

this helped me!

**Comment by lorenzosfarra** [comment]
Same problem here with Laravel v6.20.27, @zayaets solution did the trick.

**Comment by atymic** [comment]
Fixed in #38  :)
