### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/plivo#34]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by ericbae** [comment]
Any update on this?

**Comment by DanielMalmgren** [comment]
I guess we could interpret the lack of response here as this project being dead?

**Comment by atymic** [comment]
Feel free to PR support. Should probably just be changing the constraints

**Comment by koomai** [comment]
Released: https://github.com/laravel-notification-channels/plivo/releases/tag/v2.2.0
